CREATE TABLE DEPARTMENT(ID integer NOT NULL AUTO_INCREMENT, NAME VARCHAR2(20), PRIMARY KEY(ID) );

CREATE TABLE STUDENT(ID integer NOT NULL AUTO_INCREMENT, NAME VARCHAR2(20), MOBILE INTEGER, DEPT_ID INTEGER NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID));


select * from DEPARTMENT;